# Generated by Django 3.1.5 on 2021-01-19 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('block_count', models.IntegerField()),
                ('basefee', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'blockinfo',
                'verbose_name_plural': 'blockinfos',
                'db_table': 'blockinfo',
                'ordering': ['epoch'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MpoolInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('epoch', models.IntegerField()),
            ],
            options={
                'verbose_name': 'mpoolinfo',
                'verbose_name_plural': 'mpoolinfos',
                'db_table': 'mpoolinfo',
                'ordering': ['epoch'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MpoolCateInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('epoch', models.IntegerField()),
                ('cate_code', models.IntegerField()),
                ('count', models.IntegerField()),
                ('gas_limit_avg', models.BigIntegerField(blank=True, null=True)),
                ('gas_limit_total', models.BigIntegerField(blank=True, null=True)),
                ('gas_cap_avg', models.BigIntegerField(blank=True, null=True)),
                ('gas_cap_total', models.BigIntegerField(blank=True, null=True)),
                ('gas_premium_avg', models.BigIntegerField(blank=True, null=True)),
                ('gas_premium_total', models.BigIntegerField(blank=True, null=True)),
                ('value', models.BigIntegerField(blank=True, null=True)),
                ('foreign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cates', to='gas_learn.mpoolinfo')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='BlockCateInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cate_code', models.IntegerField()),
                ('count', models.IntegerField()),
                ('gas_limit_avg', models.BigIntegerField(blank=True, null=True)),
                ('gas_limit_total', models.BigIntegerField(blank=True, null=True)),
                ('gas_cap_avg', models.BigIntegerField(blank=True, null=True)),
                ('gas_cap_total', models.BigIntegerField(blank=True, null=True)),
                ('gas_premium_avg', models.BigIntegerField(blank=True, null=True)),
                ('gas_premium_total', models.BigIntegerField(blank=True, null=True)),
                ('value', models.BigIntegerField(blank=True, null=True)),
                ('foreign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cates', to='gas_learn.blockinfo')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
