# Generated by Django 3.1.5 on 2021-01-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_learn', '0002_trainingblockmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingResultModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.IntegerField()),
                ('parent_basefee', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'TrainResult',
                'verbose_name_plural': 'TrainResults',
                'db_table': 'trainResult',
                'managed': True,
            },
        ),
    ]
