# Generated by Django 3.1.5 on 2021-01-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_learn', '0003_trainingresultmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingresultmodel',
            name='delta',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingresultmodel',
            name='delta_proba',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trainingresultmodel',
            name='isPostive',
            field=models.BooleanField(default=True),
        ),
    ]
