# Generated by Django 3.1.5 on 2021-01-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_learn', '0005_traintiggermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastTiggerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.IntegerField()),
                ('isOk', models.BooleanField()),
            ],
            options={
                'verbose_name': 'ForecastTiggerModel',
                'verbose_name_plural': 'ForecastTiggerModels',
                'db_table': 'ForecastTigger',
                'managed': True,
            },
        ),
    ]
