# Generated by Django 3.1.5 on 2021-01-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_learn', '0006_forecasttiggermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.IntegerField()),
                ('empty_num', models.IntegerField()),
                ('block_count', models.IntegerField()),
                ('parent_basefee', models.BigIntegerField()),
                ('count_block', models.IntegerField()),
                ('limit_total_block', models.BigIntegerField()),
                ('limit_avg_block', models.BigIntegerField()),
                ('cap_total_block', models.BigIntegerField()),
                ('cap_avg_block', models.BigIntegerField()),
                ('premium_total_block', models.BigIntegerField()),
                ('premium_avg_block', models.BigIntegerField()),
                ('backward', models.IntegerField()),
            ],
            options={
                'verbose_name': 'ForecastModel',
                'verbose_name_plural': 'ForecastModels',
                'db_table': 'forecast_data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ForecastResultModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.IntegerField()),
                ('parent_basefee', models.BigIntegerField()),
                ('delta', models.BigIntegerField(default=0)),
                ('isPostive', models.BooleanField(default=True)),
                ('delta_proba', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'ForecastResult',
                'verbose_name_plural': 'ForecastResults',
                'db_table': 'forecast_result',
                'managed': True,
            },
        ),
    ]
