# Generated by Django 3.1.5 on 2021-01-27 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gas_learn', '0007_forecastdatamodel_forecastresultmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecastresultmodel',
            options={'managed': True, 'verbose_name': 'ForecastResultModel', 'verbose_name_plural': 'ForecastResultModels'},
        ),
        migrations.AlterModelOptions(
            name='trainingblockmodel',
            options={'managed': True, 'verbose_name': 'TrainBlockModel', 'verbose_name_plural': 'TrainBlockModels'},
        ),
        migrations.AlterModelOptions(
            name='trainingresultmodel',
            options={'managed': True, 'verbose_name': 'TrainResultModel', 'verbose_name_plural': 'TrainResultModels'},
        ),
    ]
